version: "3.9"
services:
  client: 
    build: .
    ports:
      - 4200:4200
    environment:
      WATCHPACK_POLLING: "true"  
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  test: 
    build: .
    command: ["npm", "run", "test"]
    environment:
      WATCHPACK_POLLING: "true"  
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
    stdin_open: true
    tty: true